import axios from 'axios';

export default {
    async getCandidates() {
        const data = await axios.get("https://66e8061fb17821a9d9db03c8.mockapi.io/api/v1/candidate");  
        return data.data;

        // [
        //     {
        //         key: 1,
        //         name:"Егор Б",
        //         age: "-",
        //         greid: "middle",
        //         stack: "frontend",
        //         city: "Минск",
        //         technology: "react",
        //         reit: "2500",
        //         apply: "свободен",
        //         cv : "",
        //     },
        //     {
        //         key: 2,
        //         name:"Кирилл",
        //         age: "-",
        //         greid: "middle",
        //         stack: "QA",
        //         city: "-",
        //         technology: "",
        //         reit: "2500",
        //         apply: "свободен",
        //         cv : "",
        //     },
        //     {
        //         key: 3,
        //         name:"Nbveh",
        //         age: "-",
        //         greid: "middle",
        //         stack: "QA",
        //         city: "-",
        //         technology: "",
        //         reit: "2500",
        //         apply: "свободен",
        //         cv : "",
        //     },
        //     {
        //             "key": 4,
        //             "name": "Alexander P.",
        //             "age": null,
        //             "greid": "Senior",
        //             "stack": "Fullstack web developer",
        //             "city": "Saint Petersburg, Russia",
        //             "technology": "Angular React ASP.NET Node.js",
        //             "reit": "",
        //             "apply": "Занят, но рассматриваем предложения.",
        //             "cv": "",
        //             "company":"arview",
        //         },
        //         {
        //             "key": 5,
        //             "name": "Dmitry B.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "Fullstack web developer",
        //             "city": "Tomsk, Russia",
        //             "technology": "React Node.js",
        //             "reit": "",
        //             "apply": "Может стартовать ASAP.",
        //             "cv": "",
        //             "company":"arview",
        //         },
        //         {
        //             "key": 6,
        //             "name": "Dmitry F.",
        //             "age": null,
        //             "greid": "Senior",
        //             "stack": "Android and iOS developer",
        //             "city": "Tomsk, Russia",
        //             "technology": "Native Android Native iOS Xamarin",
        //             "reit": "",
        //             "apply": "Занят, но рассматриваем предложения.",
        //             "cv": "",
        //             "company":"arview",
        //         },
        //         {
        //             "key": 6,
        //             "name": "Алексей О.",
        //             "age": null,
        //             "greid": "Senior",
        //             "stack": "Java",
        //             "city": null,
        //             "technology": [],
        //             "reit": null,
        //             "apply": null,
        //             "cv": null,
        //             "company": "foundDevs"
        //         },
        //         {
        //             "key": 7,
        //             "name": "Антон З.",
        //             "age": null,
        //             "greid": "Senior",
        //             "stack": "Manual QA",
        //             "city": null,
        //             "technology": [],
        //             "reit": null,
        //             "apply": null,
        //             "cv": null,
        //             "company": "foundDevs"
        //         },
        //         {
        //             "key": 8,
        //             "name": "Максим Ш.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "React",
        //             "city": null,
        //             "technology": [],
        //             "reit": null,
        //             "apply": null,
        //             "cv": null,
        //             "company": "foundDevs"
        //         },
        //         {
        //             "key": 9,
        //             "name": "Павел П.",
        //             "age": null,
        //             "greid": "Senior",
        //             "stack": "Fullstack (React, Node.js)",
        //             "city": null,
        //             "technology": "React Node.js",
        //             "reit": null,
        //             "apply": null,
        //             "cv": null,
        //             "company": "foundDevs"
        //         },
        //         {
        //             "key": 10,
        //             "name": "Вероника К.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "BA",
        //             "city": null,
        //             "technology": "",
        //             "reit": null,
        //             "apply": null,
        //             "cv": null,
        //             "company": "foundDevs"
        //         },
        //         {
        //             "key": 11,
        //             "name": "Григорий А.",
        //             "age": null,
        //             "greid": "Senior",
        //             "stack": "Backend",
        //             "city": "РФ, Брянск",
        //             "technology": "PHP (Laravel, Bitrix)",
        //             "reit": null,
        //             "apply": "Занят",
        //             "cv": null,
        //             "company": "wesma"
        //         },
        //         {
        //             "key": 12,
        //             "name": "Константин С.",
        //             "age": null,
        //             "greid": "Middle+",
        //             "stack": "Backend",
        //             "city": "РФ, Москва",
        //             "technology": "PHP (Bitrix)",
        //             "reit": null,
        //             "apply": "Занят",
        //             "cv": null,
        //             "company": "wesma"
        //         },
        //         {
        //             "key": 13,
        //             "name": "Илья О.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "Backend",
        //             "city": "РФ, Грузия",
        //             "technology": "PHP (Laravel)",
        //             "reit": null,
        //             "apply": "Занят",
        //             "cv": null,
        //             "company": "wesma"
        //         },
        //         {
        //             "key": 14,
        //             "name": "Syimyk Zhantoroev",
        //             "age": null,
        //             "greid": null,
        //             "stack": "DevOps engineer",
        //             "city": null,
        //             "technology": "AWS, GCP",
        //             "reit": null,
        //             "apply": "ASAP",
        //             "cv": null,
        //             "company": "Ant"
        //         },
        //         {
        //             "key": 15,
        //             "name": "Nurzada Esenbaeva",
        //             "age": null,
        //             "greid": null,
        //             "stack": "DevOps engineer",
        //             "city": null,
        //             "technology": "SRE, GCP, AWS",
        //             "reit": null,
        //             "apply": "ASAP",
        //             "cv": null,
        //             "company": "Ant"
        //         },
        //         {
        //             "key": 16,
        //             "name": "Nurmukhamed Esenbaev",
        //             "age": null,
        //             "greid": null,
        //             "stack": "DevOps engineer",
        //             "city": null,
        //             "technology": "AWS, Azure",
        //             "reit": null,
        //             "apply": "ASAP",
        //             "cv": null,
        //             "company": "Ant"
        //         },
        //         {
        //             "key": 17,
        //             "name": "Akzhol Suborov",
        //             "age": null,
        //             "greid": null,
        //             "stack": "DevOps engineer",
        //             "city": null,
        //             "technology": "Azure",
        //             "reit": null,
        //             "apply": "ASAP",
        //             "cv": null,
        //             "company": "Ant"
        //         },
        //         {
        //             "key": 18,
        //             "name": "Cholpon Abdisukhan",
        //             "age": null,
        //             "greid": null,
        //             "stack": "DevOps engineer",
        //             "city": null,
        //             "technology": "AWS, GCP",
        //             "reit": null,
        //             "apply": "ASAP",
        //             "cv": null,
        //             "company": "Ant"
        //         },
        //         {
        //             "key": 19,
        //             "name": "Beknazar Saitov",
        //             "age": null,
        //             "greid": null,
        //             "stack": "DevOps engineer",
        //             "city": null,
        //             "technology": "AWS",
        //             "reit": null,
        //             "apply": "ASAP",
        //             "cv": null,
        //             "company": "Ant"
        //         },
        //         {
        //             "key": 20,
        //             "name": "Nazim Mukhtar",
        //             "age": null,
        //             "greid": null,
        //             "stack": "DevOps engineer",
        //             "city": null,
        //             "technology": "Azure",
        //             "reit": null,
        //             "apply": "ASAP",
        //             "cv": null,
        //             "company": "Ant"
        //         },
        //         {
        //             "key": 21,
        //             "name": "Lunara Inasheva",
        //             "age": null,
        //             "greid": null,
        //             "stack": "DevOps engineer",
        //             "city": null,
        //             "technology": "GCP",
        //             "reit": null,
        //             "apply": "ASAP",
        //             "cv": null,
        //             "company": "Ant"
        //         },
        //         {
        //             "key": 22,
        //             "name": "Н. Александр Андреевич",
        //             "age": null,
        //             "greid": "senior",
        //             "stack": "java",
        //             "city": null,
        //             "technology": null,
        //             "reit": "2580.00",
        //             "apply": "Актуален",
        //             "cv": null,
        //             "company": "kesmaty"
        //         },
        //         {
        //             "key": 23,
        //             "name": "С. Дмитрий",
        //             "age": null,
        //             "greid": "middle+",
        //             "stack": "QA",
        //             "city": null,
        //             "technology": null,
        //             "reit": "2760.00",
        //             "apply": "Актуален",
        //             "cv": null,
        //             "company": "kesmaty"
        //         },
        //         {
        //             "key": 24,
        //             "name": "И. Роман Андреевич",
        //             "age": null,
        //             "greid": "middle+",
        //             "stack": "java",
        //             "city": null,
        //             "technology": null,
        //             "reit": "2760.00",
        //             "apply": "Актуален",
        //             "cv": null,
        //             "company": "kesmaty"
        //         },
        //         {
        //             "key": 25,
        //             "name": "З. Альберт",
        //             "age": null,
        //             "greid": "middle+",
        //             "stack": "React",
        //             "city": null,
        //             "technology": null,
        //             "reit": "1920.00",
        //             "apply": "Актуален",
        //             "cv": null,
        //             "company": "kesmaty"
        //         },
        //         {
        //             "key": 26,
        //             "name": "С. Михаил",
        //             "age": null,
        //             "greid": "middle+",
        //             "stack": "java",
        //             "city": null,
        //             "technology": null,
        //             "reit": "2400.00",
        //             "apply": "Актуален",
        //             "cv": null,
        //             "company": "kesmaty"
        //         },
        //         {
        //             "key": 27,
        //             "name": "С. Дмитрий",
        //             "age": null,
        //             "greid": "senior",
        //             "stack": "java",
        //             "city": null,
        //             "technology": null,
        //             "reit": "3600.00",
        //             "apply": "Актуален",
        //             "cv": null,
        //             "company": "kesmaty"
        //         },
        //         {
        //             "key": 28,
        //             "name": "Ч. Андрей",
        //             "age": null,
        //             "greid": "senior",
        //             "stack": "Fullstack",
        //             "city": null,
        //             "technology": null,
        //             "reit": "3360.00",
        //             "apply": "Актуален",
        //             "cv": null,
        //             "company": "kesmaty"
        //         },
        //         {
        //             "key": 29,
        //             "name": "П. Александр",
        //             "age": null,
        //             "greid": "middle+",
        //             "stack": "QA",
        //             "city": null,
        //             "technology": null,
        //             "reit": "1860.00",
        //             "apply": "Актуален",
        //             "cv": null,
        //             "company": "kesmaty"
        //         },
        //         {
        //             "key": 30,
        //             "name": "П. Игорь",
        //             "age": null,
        //             "greid": "middle+",
        //             "stack": "java",
        //             "city": null,
        //             "technology": null,
        //             "reit": "2940.00",
        //             "apply": "Актуален",
        //             "cv": null,
        //             "company": "kesmaty"
        //         },
        //         {
        //             "key": 31,
        //             "name": "Х. Григорий",
        //             "age": null,
        //             "greid": "senior",
        //             "stack": ".Net",
        //             "city": null,
        //             "technology": null,
        //             "reit": "2580.00",
        //             "apply": "Актуален",
        //             "cv": null,
        //             "company": "kesmaty"
        //         },
        //         {
        //             "key": 32,
        //             "name": "Щ. Владислав",
        //             "age": null,
        //             "greid": "senior",
        //             "stack": "SA",
        //             "city": null,
        //             "technology": null,
        //             "reit": "3000.00",
        //             "apply": "Актуален",
        //             "cv": null,
        //             "company": "kesmaty"
        //         },
        //         {
        //             "key": 33,
        //             "name": "К. Владислав",
        //             "age": null,
        //             "greid": "senior",
        //             "stack": "java",
        //             "city": null,
        //             "technology": null,
        //             "reit": "4380.00",
        //             "apply": "Актуален",
        //             "cv": null,
        //             "company": "kesmaty"
        //         },
        //         {
        //             "key": 34,
        //             "name": "И. Юрий",
        //             "age": null,
        //             "greid": "middle+",
        //             "stack": "Python",
        //             "city": null,
        //             "technology": null,
        //             "reit": "2460.00",
        //             "apply": "Актуален",
        //             "cv": null,
        //             "company": "kesmaty"
        //         },
        //         {
        //             "key": 35,
        //             "name": "А. Влад",
        //             "age": null,
        //             "greid": "middle+",
        //             "stack": "Python",
        //             "city": null,
        //             "technology": null,
        //             "reit": "2160.00",
        //             "apply": "Актуален",
        //             "cv": null,
        //             "company": "kesmaty"
        //         },
        //         {
        //             "key": 36,
        //             "name": "Т. Алексей",
        //             "age": null,
        //             "greid": "middle+",
        //             "stack": "java",
        //             "city": null,
        //             "technology": null,
        //             "reit": "3000.00",
        //             "apply": "Актуален",
        //             "cv": null,
        //             "company": "kesmaty"
        //         },
        //         {
        //             "key": 37,
        //             "name": "А. Иса",
        //             "age": null,
        //             "greid": "middle+",
        //             "stack": "java",
        //             "city": null,
        //             "technology": null,
        //             "reit": "2460.00",
        //             "apply": "Актуален",
        //             "cv": null,
        //             "company": "kesmaty"
        //         },
        //         {
        //             "key": 38,
        //             "name": "Софья Л.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "Designer",
        //             "city": null,
        //             "technology": null,
        //             "reit": "2160.00",
        //             "apply": "свободен с 25.09",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 39,
        //             "name": "Мария П.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "Designer",
        //             "city": null,
        //             "technology": null,
        //             "reit": "2160.00",
        //             "apply": "свободен с 23.09",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 40,
        //             "name": "Евгений Г.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "Backend PHP Bitrix",
        //             "city": null,
        //             "technology": null,
        //             "reit": "3000.00",
        //             "apply": "Готов сейчас (now)",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 41,
        //             "name": "Александр А.",
        //             "age": null,
        //             "greid": "Junior",
        //             "stack": "Frontend React.js",
        //             "city": null,
        //             "technology": null,
        //             "reit": "1680.00",
        //             "apply": "Готов сейчас (now)",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 42,
        //             "name": "Нурсултан Б.",
        //             "age": null,
        //             "greid": "Middle+",
        //             "stack": "Frontend React.js",
        //             "city": null,
        //             "technology": null,
        //             "reit": "3240.00",
        //             "apply": "Готов сейчас (now)",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 43,
        //             "name": "Вячеслав Б.",
        //             "age": null,
        //             "greid": "Senior",
        //             "stack": "Frontend Vue.js",
        //             "city": null,
        //             "technology": null,
        //             "reit": "3360.00",
        //             "apply": "свободен с 07.10",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 44,
        //             "name": "Первак А.",
        //             "age": null,
        //             "greid": "Middle+",
        //             "stack": "Frontend Vue.js",
        //             "city": null,
        //             "technology": null,
        //             "reit": "3000.00",
        //             "apply": "свободен с 07.10",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 45,
        //             "name": "Владислав Ш.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "Frontend Vue.js",
        //             "city": null,
        //             "technology": null,
        //             "reit": "2880.00",
        //             "apply": "Доступен на 4 часа",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 46,
        //             "name": "Александр Н.",
        //             "age": null,
        //             "greid": "Junior",
        //             "stack": "Kotlin",
        //             "city": null,
        //             "technology": null,
        //             "reit": "2160.00",
        //             "apply": "Готов сейчас (now)",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 47,
        //             "name": "Андрей Е.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "Kotlin",
        //             "city": null,
        //             "technology": null,
        //             "reit": "3120.00",
        //             "apply": "Готов сейчас (now)",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 48,
        //             "name": "Дмитрий Ф.",
        //             "age": null,
        //             "greid": "Senior",
        //             "stack": "Swift",
        //             "city": null,
        //             "technology": null,
        //             "reit": "3240.00",
        //             "apply": "Готов сейчас (now)",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 49,
        //             "name": "Анастасия Б.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "Analyst Bitrix24",
        //             "city": null,
        //             "technology": null,
        //             "reit": "2880.00",
        //             "apply": "Готов сейчас (now)",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 50,
        //             "name": "Дмитрий М.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "Analyst",
        //             "city": null,
        //             "technology": null,
        //             "reit": "2880.00",
        //             "apply": "Готов сейчас (now)",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 51,
        //             "name": "Анастасия З.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "1C Analytics",
        //             "city": null,
        //             "technology": null,
        //             "reit": "3480.00",
        //             "apply": "Свободна на 2 часа",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 52,
        //             "name": "Ксения К.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "1C developer",
        //             "city": null,
        //             "technology": null,
        //             "reit": "3480.00",
        //             "apply": "Готов сейчас (now)",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 53,
        //             "name": "Сергей В.",
        //             "age": null,
        //             "greid": "Senior",
        //             "stack": "Python",
        //             "city": null,
        //             "technology": null,
        //             "reit": "3840.00",
        //             "apply": "свободен с 01.10",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 54,
        //             "name": "Кирилл О.",
        //             "age": null,
        //             "greid": "Middle+",
        //             "stack": "Python",
        //             "city": null,
        //             "technology": null,
        //             "reit": "3600.00",
        //             "apply": "свободен с 01.10",
        //             "cv": null,
        //             "company": "zembrains"
        //         },
        //         {
        //             "key": 55,
        //             "name": "Сергей",
        //             "age": null,
        //             "greid": "Middle+",
        //             "stack": "Frontend",
        //             "city": null,
        //             "technology": "ReactJS, NextJS, ReactNative, TypeScript, Next.js, TailwindCSS",
        //             "reit": "2640.00",
        //             "apply": "CV Сергей",
        //             "cv": null,
        //             "company": "QDigital"
        //         },
        //         {
        //             "key": 56,
        //             "name": "Андрей",
        //             "age": null,
        //             "greid": "Middle+",
        //             "stack": "Fullstack (упор backend)",
        //             "city": null,
        //             "technology": "Laravel, Symphony, NextJs, ReactJs, Redis, Docker, MySQL, PostgreSQL",
        //             "reit": "2640.00",
        //             "apply": "CV Андрей",
        //             "cv": null,
        //             "company": "QDigital"
        //         },
        //         {
        //             "key": 57,
        //             "name": "Дмитрий",
        //             "age": null,
        //             "greid": "Middle+",
        //             "stack": "Backend Developer",
        //             "city": null,
        //             "technology": "Laravel, CodeIgniter, Vtiger, SocialEngine",
        //             "reit": "2640.00",
        //             "apply": "CV Дмитрий",
        //             "cv": null,
        //             "company": "QDigital"
        //         },
        //         {
        //             "key": 58,
        //             "name": "Борис С.",
        //             "age": null,
        //             "greid": "Middle+",
        //             "stack": "Java",
        //             "city": "РФ, Москва",
        //             "technology": "Java",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 59,
        //             "name": "Мария М.",
        //             "age": null,
        //             "greid": "Middle+",
        //             "stack": "Java",
        //             "city": "РФ, Рыбинск",
        //             "technology": "Java, JavaScript",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 60,
        //             "name": "Ольга М.",
        //             "age": null,
        //             "greid": "Middle+ / Senior",
        //             "stack": "Java",
        //             "city": "РФ, Тольятти",
        //             "technology": "Java, Kotlin, Python",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 61,
        //             "name": "Константин Н.",
        //             "age": null,
        //             "greid": "Senior / Team Lead",
        //             "stack": "Java",
        //             "city": "РФ, Тольятти",
        //             "technology": "Java, Kotlin",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 62,
        //             "name": "Евгений Б.",
        //             "age": null,
        //             "greid": "Senior",
        //             "stack": "Java",
        //             "city": "РФ, Тюмень",
        //             "technology": "Java, Kotlin",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 63,
        //             "name": "Александр Б.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "Java",
        //             "city": "РФ, Москва",
        //             "technology": "Java, Spring Framework, PostgreSQL, JPA Apache, Maven, Lombok",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 64,
        //             "name": "Геннадий Я.",
        //             "age": null,
        //             "greid": "Senior",
        //             "stack": "Java",
        //             "city": "РФ, Тольятти",
        //             "technology": "Java, Kotlin; Linux (Ubuntu)",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 65,
        //             "name": "Агил Г.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "Manual",
        //             "city": "РФ, Самара",
        //             "technology": "DevTools, Postman, Swagger, SoapUI",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 66,
        //             "name": "Анна С.",
        //             "age": null,
        //             "greid": "Senior / Team Lead",
        //             "stack": "Manual",
        //             "city": "РФ, Тольятти",
        //             "technology": "Postman, Swagger, Devtools",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 67,
        //             "name": "Дмитрий Ш.",
        //             "age": null,
        //             "greid": "Middle+/Senior",
        //             "stack": "Auto/Manual",
        //             "city": "РФ, Новороссийск",
        //             "technology": "Postman, Swagger, Fiddler, Charles, DBeaver",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 68,
        //             "name": "Михаил Г.",
        //             "age": null,
        //             "greid": "Middle+",
        //             "stack": "DevOps",
        //             "city": "РФ, Тольятти",
        //             "technology": "Python, Bash, AWS, SberCloud, Hetzner, Proxmox",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 69,
        //             "name": "Григорий М.",
        //             "age": null,
        //             "greid": "Middle+",
        //             "stack": "DevOps",
        //             "city": "РФ, Ижевск",
        //             "technology": "Bash, GitLab CI, Docker, Docker Compose, K8S, Helm, Ansible, PostgreSQL, MongoDB, MySQL, MinIO, RabbitMQ, Redis, Git, Docker, VS Code",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 70,
        //             "name": "Степан Б.",
        //             "age": null,
        //             "greid": "Middle+",
        //             "stack": "React",
        //             "city": "РФ, Ярославль",
        //             "technology": "JavaScript, TypeScript",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 71,
        //             "name": "Вадим К.",
        //             "age": null,
        //             "greid": "Middle+",
        //             "stack": "React",
        //             "city": "РФ, Кемерово",
        //             "technology": "JavaScript, TypeScript",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 72,
        //             "name": "Иван Д.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "React",
        //             "city": "РФ, Тольятти",
        //             "technology": "JavaScript, TypeScript",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 73,
        //             "name": "Станислав А.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "React",
        //             "city": "РФ, Тольятти",
        //             "technology": "JavaScript, TypeScript",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 74,
        //             "name": "Владимир Б.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "React",
        //             "city": "РФ, Уфа",
        //             "technology": "JavaScript, TypeScript",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 75,
        //             "name": "Антон С.",
        //             "age": null,
        //             "greid": "Senior",
        //             "stack": "React",
        //             "city": "РФ, Тольятти",
        //             "technology": "JavaScript, TypeScript",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 76,
        //             "name": "Магомед М.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "React",
        //             "city": "РФ, Грозный",
        //             "technology": "JavaScript, TypeScript",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 77,
        //             "name": "Алексей П.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "System Analyst",
        //             "city": "РФ, Москва",
        //             "technology": "REST API, JSON, SQL, RabbitMQ, Kafka, PostgreSQL, MySQL, Jira, Confluence, Soap, Postman, Swagger, ESB",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 78,
        //             "name": "Сергей К.",
        //             "age": null,
        //             "greid": "Middle+",
        //             "stack": "System Analyst",
        //             "city": "РФ, Воронеж",
        //             "technology": null,
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 79,
        //             "name": "Михаил Г.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "System Analyst",
        //             "city": "РФ, Череповец",
        //             "technology": "StarUML, Swagger OpenAPI, Postman",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 80,
        //             "name": "Дмитрий А.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "System Analyst",
        //             "city": "Грузия, Тбилиси",
        //             "technology": "Figma, dbeaver, Aris, jira, confluence, Visio, Kafka",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 81,
        //             "name": "Егор П.",
        //             "age": null,
        //             "greid": "Middle",
        //             "stack": "Flutter",
        //             "city": "РФ, Тольятти",
        //             "technology": "Flutter, BLoC, GraphQL, GetIt, Injectable, Hive",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 82,
        //             "name": "Андрей В.",
        //             "age": null,
        //             "greid": "Senior/Lead",
        //             "stack": "Flutter",
        //             "city": "Армения, Ереван",
        //             "technology": "Flutter, BLoC, GraphQL, GetIt, Injectable, Hive",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 83,
        //             "name": "Андрей М.",
        //             "age": null,
        //             "greid": "Senior/Lead",
        //             "stack": "Flutter",
        //             "city": "Армения, Ереван",
        //             "technology": "Flutter, BLoC, GraphQL, GetIt, Injectable, Hive",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },
        //         {
        //             "key": 84,
        //             "name": "Юлия К.",
        //             "age": null,
        //             "greid": "Middle/Middle+",
        //             "stack": "UX/UI | Web",
        //             "city": "РБ, Слуцк",
        //             "technology": "Figma, Adobe Photoshop, Adobe Illustrator, Adobe After Effect",
        //             "cv": null,
        //             "company": "Cosysoft"
        //         },  
        //     ];

        // console.log("candidateAPI");
        // let candidateFromServer = [];
        // console.log(this.candidateFromServer);
        // console.log("e");
        // return this.candidateFromServer;
    }
}