openapi: 3.0.0
info:
title: Vacancy API
description: API для управления вакансиями
version: 1.0.0
paths:
/api/vacancy:
    post:
     summary: Создать новую вакансию
     description: Создает новую вакансию с предоставленными данными
     requestBody:
        required: true
        content:
         application/json:
            schema:
             type: object
             properties:
                sector:
                 type: string
                 example: "Финансовые услуги"
                position:
                 type: string
                 example: "Специалист по анализу данных"
                rate:
                 type: number
                 example: 4500
                specialists:
                 type: integer
                 example: 5
                attractionPeriod:
                 type: string
                 example: "3 месяца"
                workFormat:
                 type: string
                 example: "Гибридный"
                region:
                 type: string
                 example: "Санкт-Петербург"
                responseTime:
                 type: string
                 example: "7 дней"
                paymentTerm:
                 type: string
                 example: "45 дней"
                industry:
                 type: string
                 example: "Информационные технологии"
                rating:
                 type: number
                 example: 4.0
                reviews:
                 type: integer
                 example: 85
                mandatoryRequirements:
                 type: string
                 example: "Опыт работы с большими данными, знание Python и SQL"
                additionalRequirements:
                 type: string
                 example: "Опыт работы с облачными платформами, знание машинного обучения"
                projectTasks:
                 type: string
                 example: "Разработка аналитических моделей, автоматизация отчетности"
                projectDescription:
                 type: string
                 example: "Проект направлен на оптимизацию бизнес-процессов с использованием аналитики данных"
                team:
                 type: string
                 example: "12 человек, включая аналитиков, разработчиков и менеджеров проектов"
                projectConditions:
                 type: string
                 example: "Подписание договора о конфиденциальности, наличие собственного оборудования"
     responses:
        '201':
         description: Вакансия успешно создана
         content:
            application/json:
             schema:
                type: object
                properties:
                 id:
                    type: integer
                    example: 1
        '400':
         description: Неверный запрос
        '500':
         description: Внутренняя ошибка сервера

/api/vacancy/{id}:
    post:
     summary: Получить, обновить или удалить вакансию
     description: Получает, обновляет или удаляет вакансию в зависимости от переданных параметров
     parameters:
        - name: id
         in: path
         required: true
         description: Уникальный идентификатор вакансии
         schema:
            type: integer
     requestBody:
        required: false
        content:
         application/json:
            schema:
             type: object
             properties:
                action:
                 type: string
                 enum: [read, update, delete]
                 example: "read"
                data:
                 type: object
                 properties:
                    sector:
                     type: string
                     example: "Финансовые услуги"
                    position:
                     type: string
                     example: "Специалист по анализу данных"
                    rate:
                     type: number
                     example: 4500
                    specialists:
                     type: integer
                     example: 5
                    attractionPeriod:
                     type: string
                     example: "3 месяца"
                    workFormat:
                     type: string
                     example: "Гибридный"
                    region:
                     type: string
                     example: "Санкт-Петербург"
                    responseTime:
                     type: string
                     example: "7 дней"
                    paymentTerm:
                     type: string
                     example: "45 дней"
                    industry:
                     type: string
                     example: "Информационные технологии"
                    rating:
                     type: number
                     example: 4.0
                    reviews:
                     type: integer
                     example: 85
                    mandatoryRequirements:
                     type: string
                     example: "Опыт работы с большими данными, знание Python и SQL"
                    additionalRequirements:
                     type: string
                     example: "Опыт работы с облачными платформами, знание машинного обучения"
                    projectTasks:
                     type: string
                     example: "Разработка аналитических моделей, автоматизация отчетности"
                    projectDescription:
                     type: string
                     example: "Проект направлен на оптимизацию бизнес-процессов с использованием аналитики данных"
                    team:
                     type: string
                     example: "12 человек, включая аналитиков, разработчиков и менеджеров проектов"
                    projectConditions:
                     type: string
                     example: "Подписание договора о конфиденциальности, наличие собственного оборудования"
     responses:
        '200':
         description: Успешный ответ
         content:
            application/json:
             schema:
                type: object
                properties:
                 id:
                    type: integer
                    example: 1
                 sector:
                    type: string
                    example: "Финансовые услуги"
                 position:
                    type: string
                    example: "Специалист по анализу данных"
                 rate:
                    type: number
                    example: 4500
                 specialists:
                    type: integer
                    example: 5
                 attractionPeriod:
                    type: string
                    example: "3 месяца"
                 workFormat:
                    type: string
                    example: "Гибридный"
                 region:
                    type: string
                    example: "Санкт-Петербург"
                 responseTime:
                    type: string
                    example: "7 дней"
                 paymentTerm:
                    type: string
                    example: "45 дней"
                 industry:
                    type: string
                    example: "Информационные технологии"
                 rating:
                    type: number
                    example: 4.0
                 reviews:
                    type: integer
                    example: 85
                 mandatoryRequirements:
                    type: string
                    example: "Опыт работы с большими данными, знание Python и SQL"
                 additionalRequirements:
                    type: string
                    example: "Опыт работы с облачными платформами, знание машинного обучения"
                 projectTasks:
                    type: string
                    example: "Разработка аналитических моделей, автоматизация отчетности"
                 projectDescription:
                    type: string
                    example: "Проект направлен на оптимизацию бизнес-процессов с использованием аналитики данных"
                 team:
                    type: string
                    example: "12 человек, включая аналитиков, разработчиков и менеджеров проектов"
                 projectConditions:
                    type: string
                    example: "Подписание договора о конфиденциальности, наличие собственного оборудования"
        '400':
         description: Неверный запрос
        '404':
         description: Вакансия не найдена
        '500':
         description: Внутренняя ошибка сервера